In [31]:
import numpy as np
np.random.seed(0)

In [32]:
N, D = 100, 2

In [33]:
X = np.random.randn(N,D)

In [34]:
X

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252],
       [-0.88778575, -1.98079647],
       [-0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985],
       [-0.38732682, -0.30230275],
       [-1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036],
       [-1.61389785, -0.21274028],
       [-0.89546656,  0.3869025 ],
       [-0.51080514, -1.18063218],
       [-0.02818223,  0.42833187],
       [ 0.06651722,

In [35]:
X[:50,:] = X[:50,:] - 2*np.ones((50,D))
X[50:,:] = X[50:,:] + 2*np.ones((50,D))

In [36]:
Y = np.array([0]*50 + [1]*50)

In [37]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
Y.shape

(100,)

In [39]:
ones = np.ones((N, 1))
Xb = np.concatenate((ones, X), axis=1)
w = np.random.randn(D + 1)

z = Xb.dot(w)

In [40]:
z.shape

(100,)

In [41]:
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

In [42]:
Yhat = sigmoid(z)

In [43]:
Yhat

array([0.11184986, 0.5349896 , 0.02630164, 0.07701481, 0.16610108,
       0.37167963, 0.10544677, 0.13834956, 0.06458559, 0.04294671,
       0.31867838, 0.04258236, 0.01431002, 0.09058319, 0.30135292,
       0.15303615, 0.01703293, 0.13769961, 0.25691978, 0.08871273,
       0.0322868 , 0.613937  , 0.07947694, 0.28193677, 0.12593916,
       0.19001302, 0.03676468, 0.16631429, 0.14516352, 0.08812144,
       0.08914206, 0.02202264, 0.07082816, 0.23315089, 0.13998289,
       0.10693535, 0.02365181, 0.0502536 , 0.07461768, 0.12418302,
       0.30571535, 0.02002476, 0.41067721, 0.07110923, 0.33762661,
       0.3432246 , 0.25623524, 0.19812424, 0.4679424 , 0.15735103,
       0.35859114, 0.93828421, 0.97745683, 0.65213677, 0.925472  ,
       0.86996677, 0.97486309, 0.90870814, 0.72195268, 0.90189808,
       0.513073  , 0.939264  , 0.79463549, 0.97037622, 0.83733277,
       0.89365882, 0.82459619, 0.90442894, 0.72796009, 0.51364353,
       0.89948689, 0.8818221 , 0.86050728, 0.94257996, 0.76111

In [44]:
def crossEntropy(Y, Yhat):
    E = 0
    for i in range(len(Y)):
        if Y[i] == 1:
            E -= np.log(Yhat[i])
        else:
            E -= np.log(1-Yhat[i])
    return E

In [45]:
w = [0, 4, 4]

In [46]:
z = Xb.dot(w)

Yhat = sigmoid(z)

In [47]:
crossEntropy(Y, Yhat)

0.16014267317718395